apiVersion: v1
kind: Service
metadata:
  name: studyvisit-2023
  labels:
    app: studyvisit-2023
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: studyvisit-2023
  type: ClusterIP
