apiVersion: apps/v1
kind: Deployment
metadata:
  name: roundcube
  namespace: default
  labels:
    app: roundcube
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: roundcube
  strategy:
    type: Recreate
  template:
    metadata:
      name: roundcube
      labels:
        app: roundcube
        version: 1.3-fpm
    spec:
      containers:
      - name: roundcube
        image: instrumentisto/roundcube:1.3-fpm
        imagePullPolicy: Always
        env:
        - name: SHARE_APP
          value: "1"
        volumeMounts:
        - mountPath: /app/config/config.inc.php
          name: secret
          readOnly: true
          subPath: roundcube.config.php
        - mountPath: /app/plugins/managesieve/config.inc.php
          name: config
          readOnly: true
          subPath: managesieve.config.php
        - mountPath: /shared
          name: src
        - mountPath: /shared/temp
          name: temp
      - name: nginx
        image: nginx:stable
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/nginx/conf.d/default.conf
          name: config
          readOnly: true
          subPath: nginx.conf
        - mountPath: /var/www
          name: src
          readOnly: true
      securityContext:
        runAsUser: 0
      volumes:
      - name: secret
        secret:
          secretName: roundcube
          defaultMode: 420
      - name: config
        configMap:
          name: roundcube
          defaultMode: 420
      - name: src
        emptyDir: {}
      - name: temp
        emptyDir: {}
