apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: studyvisit
  namespace: default
spec:
  rules:
    - host: studyvisit.ch.tudelft.nl
      http:
        paths:
          - path: /2023
            pathType: Prefix
            backend:
              service:
                name: studyvisit-2023
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: studyvisit-2023
                port:
                  number: 80
  tls:
    - hosts:
        - studyvisit.ch.tudelft.nl
      secretName: ingress-ext-tls
