apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: studyvisit
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 256m
spec:
  rules:
    - host: studyvisit.ch.tudelft.nl
      http:
        paths:
          - path: "/2023"
            backend:
              serviceName: studyvisit-2023
              servicePort: 80
          - path: "/"
            backend:
              serviceName: studyvisit-2023
              servicePort: 80
  tls:
    - hosts:
        - studyvisit.ch.tudelft.nl
      secretName: ingress-ext-tls
