---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: member-registration
  namespace: w3cie
  labels:
    app: member-registration
  annotations:
    fluxcd.io/automated: 'true'
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: member-registration
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      name: member-registration
      labels:
        app: member-registration
    spec:
      containers:
      - name: member-registration
        env:
        - name: MANAGEMENT_CONTEXT_PATH
          value: /management
        - name: MANAGEMENT_ENDPOINTS_ENABLED
          value: "false"
        - name: MANAGEMENT_ENDPOINTS_HEALTH_ENABLED
          value: "true"
        - name: SERVER_PORT
          value: "9000"
        - name: SERVER_SERVLET_CONTEXT_PATH
          value: /register
        - name: SPRING_MAIL_HOST
          value: ch.tudelft.nl
        - name: SPRING_MAIL_PORT
          value: "25"
        - name: JAVA_OPTS
          value: -Xms512m -Xmx512m -javaagent:/opt/datadog/dd-java-agent.jar
        - name: SPRING_PROFILES_ACTIVE
          value: production
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://joost.chnet/member-registration?ssl=true&sslrootcert=/usr/local/share/ca-certificates/wisvch.crt
        - name: SPRING_DATASOURCE_USERNAME
          value: member-registration
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: member-registration
              key: datasource-password
        - name: WISVCH_CONNECT_ADMIN_GROUPS
          value: chbeheer,dienst2,epa
        - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_WISVCHCONNECT_CLIENT_URI
          value: https://ch.tudelft.nl/register
        - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_WISVCHCONNECT_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: member-registration
              key: connect-client-id
        - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_WISVCHCONNECT_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: member-registration
              key: connect-client-secret
        - name: WISVCH_PAYMENTS_ISSUERURI
          value: http://payments.default/payments
        - name: WISVCH_PAYMENTS_CLIENTURI
          value: https://ch.tudelft.nl/register
        - name: DIENST_URL
          value: http://dienst2.default/
        - name: DIENST_TOKEN
          valueFrom:
            secretKeyRef:
              name: member-registration
              key: dienst-api-token
        - name: DD_SERVICE_NAME
          value: member-registration
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: DD_TRACE_SPAN_TAGS
          value: env:production
        - name: DD_SERVICE_MAPPING
          value: postgresql:member-registration-postgresql
        image: ghcr.io/wisvch/member-registration:20220302-f02579d
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9000
          name: http
          protocol: TCP
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /register/actuator/health
            port: http
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /register/actuator/health
            port: http
            scheme: HTTP
          initialDelaySeconds: 40
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 500m
            memory: 1000Mi
          requests:
            cpu: 200m
            memory: 1000Mi
