---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedback-tool
  namespace: default
  labels:
    app: feedback-tool
  annotations:
    fluxcd.io/automated: 'true'
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: feedback-tool
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      name: feedback-tool
      labels:
        app: feedback-tool
    spec:
      containers:
      - name: feedback-tool
        env:
        - name: JAVA_OPTS
          value: -Xms200m -Xmx200m -javaagent:/opt/datadog/dd-java-agent.jar
        - name: SERVER_PORT
          value: "8080"
        - name: SPRING_PROFILES_ACTIVE
          value: production
        - name: SERVER_SERVLET_CONTEXT_PATH
          value: /feedback
        - name: SERVER_USE_FORWARD_HEADERS
          value: "true"
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://joost.chnet/feedbacktool?ssl=true&sslrootcert=/usr/local/share/ca-certificates/wisvch.crt
        - name: SPRING_DATASOURCE_USERNAME
          value: feedbacktool
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: validate
        - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_WISVCHCONNECT_CLIENT_ID
          value: feedback-tool
        - name: WISVCH_RECAPTCHA_VERIFYURI
          value: https://www.google.com/recaptcha/api/siteverify
        - name: DD_SERVICE_NAME
          value: feedback-tool
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: DD_TRACE_SPAN_TAGS
          value: env:production
        - name: DD_SERVICE_MAPPING
          value: postgresql:feedback-tool-postgresql
        envFrom:
        - secretRef:
            name: feedback-tool
        image: quay.io/wisvch/feedback-tool:159
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /feedback/actuator/health
            port: http
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 1
          httpGet:
            path: /feedback/actuator/health
            port: http
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            memory: 600Mi
          requests:
            cpu: 50m
            memory: 600Mi
