apiVersion: v1
kind: Service
metadata:
  name: feedback-tool
  namespace: default
  labels:
    app: feedback-tool
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: feedback-tool
  type: ClusterIP
