apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
  name: nwerc
  namespace: default
spec:
  rules:
    - host: 2022.nwerc.eu
      http:
        paths:
          - backend:
              serviceName: nwerc-2022
              servicePort: http
  tls:
    - hosts:
        - 2022.nwerc.eu
      secretName: ingress-ext-tls-nwerc
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/temporal-redirect: https://2022.nwerc.eu$request_uri
  name: redirect-nwerc
  namespace: default
spec:
  rules:
  - host: nwerc.eu
  - host: www.nwerc.eu
  tls:
  - hosts:
    - nwerc.eu
    - www.nwerc.eu
    secretName: ingress-ext-tls-nwerc
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: ingress-ext-tls-nwerc
  namespace: default
spec:
  secretName: ingress-ext-tls-nwerc
  dnsNames:
    - nwerc.eu
    - www.nwerc.eu
    - 2022.nwerc.eu
    - www.2022.nwerc.eu
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
