---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: symposium-2022
  namespace: default
  labels:
    app: symposium-2022
  annotations:
    fluxcd.io/automated: 'true'
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: symposium-2022
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      name: symposium-2022
      labels:
        app: symposium-2022
    spec:
      containers:
      - name: symposium-2022
        image: ghcr.io/wisvch/symposium-2022:20221004-9f1dc9f
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 2
        readinessProbe:
          failureThreshold: 1
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 2
        resources:
          limits:
            memory: 64Mi
          requests:
            cpu: 10m
            memory: 32Mi
        securityContext:
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
        volumeMounts:
        - mountPath: /tmp
          name: tmpfs
      restartPolicy: Always
      securityContext:
        runAsNonRoot: false
      volumes:
      - emptyDir:
          medium: Memory
        name: tmpfs
