kind: Service
apiVersion: v1
metadata:
  name: connect-gke
spec:
  ports:
  - protocol: TCP
    port: 443
---
apiVersion: v1
kind: Endpoints
metadata:
  name: connect-gke
subsets:
- addresses:
  - ip: 34.141.157.28
  ports:
  - port: 433
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: connect
  namespace: default
  # annotations:
    # nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    # nginx.ingress.kubernetes.io/upstream-vhost: "connect.wisv.ch"
spec:
  rules:
  - host: connect.ch.tudelft.nl
    http:
      paths:
      - backend:
          serviceName: connect
          servicePort: 80
  tls:
  - hosts:
    - connect.ch.tudelft.nl
    secretName: ingress-ext-tls
