---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lancie-api
  namespace: lancie
  labels:
    app: lancie-api
  annotations:
    fluxcd.io/automated: 'true'
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: lancie-api
  strategy:
    type: Recreate
  template:
    metadata:
      name: lancie-api
      labels:
        app: lancie-api
    spec:
      containers:
      - name: lancie-api
        image: ghcr.io/areafiftylan/lancie-api:20220408-b1d5bb7
        imagePullPolicy: IfNotPresent
        env:
        - name: JAVA_OPTS
          value: -Xms128M -Xmx128M -Djava.security.egd=file:/dev/./urandom -XX:+ExitOnOutOfMemoryError
        - name: SPRING_PROFILES_ACTIVE
          value: production
        - name: SERVER_PORT
          value: "8080"
        - name: SPRING_MAIL_HOST
          value: ch.tudelft.nl
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://joost.chnet:5432/areafiftylan?ssl=true&sslrootcert=/usr/local/share/ca-certificates/wisvch.crt
        - name: SPRING_DATASOURCE_USERNAME
          value: areafiftylan
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: datasource-password
              name: lancie-api
        - name: A5L_MOLLIEKEY
          valueFrom:
            secretKeyRef:
              key: mollie-key
              name: lancie-api
        - name: A5L_GOOGLEMAPSAPIKEY
          valueFrom:
            secretKeyRef:
              key: google-maps-key
              name: lancie-api
        ports:
        - containerPort: 8080
          protocol: TCP
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/v1/management/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /api/v1/management/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: "1"
            memory: 512Mi
