kind: Service
apiVersion: v1
metadata:
  name: gcloud
spec:
  ports:
  - protocol: TCP
    port: 80
---
apiVersion: v1
kind: Endpoints
metadata:
  name: gcloud
subsets:
- addresses:
  - ip: 34.141.157.28
  ports:
  - port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: website
  namespace: default
spec:
  externalName: website.w3cie.svc.cluster.local
  type: ExternalName
---
apiVersion: v1
kind: Service
metadata:
  name: choice
  namespace: default
spec:
  externalName: choice.w3cie.svc.cluster.local
  type: ExternalName
---
apiVersion: v1
kind: Service
metadata:
  name: member-registration
  namespace: default
spec:
  externalName: member-registration.w3cie.svc.cluster.local
  type: ExternalName
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 32M
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^/events(.*)$ https://events.wisv.ch$1;
      rewrite ^/choice2(.*)$ https://choice.wisv.ch$1;
      rewrite ^/wiki(.*)$ https://wiki.wisv.ch$1;
  name: ch
  namespace: default
spec:
  rules:
    - host: ch.tudelft.nl
      http:
        paths:
          - path: /password/
            backend:
              serviceName: modify-password
              servicePort: 80
          - path: /certs/
            backend:
              serviceName: www-misc
              servicePort: 80
          - path: /register/
            backend:
              serviceName: member-registration
              servicePort: 80
          - path: /
            backend:
              serviceName: website
              servicePort: 80
  tls:
    - hosts:
        - ch.tudelft.nl
        - www.ch.tudelft.nl
      secretName: ingress-ext-tls
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/temporal-redirect: https://ch.tudelft.nl/wiki/chmanual:externetoegangank
  name: files
  namespace: default
spec:
  rules:
    - host: files.ch.tudelft.nl
  tls:
    - hosts:
        - files.ch.tudelft.nl
      secretName: ingress-ext-tls
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/temporal-redirect: https://ch.tudelft.nl
  name: redirect-ch
  namespace: default
spec:
  rules:
    - host: ch.ewi.tudelft.nl
    - host: ch.its.tudelft.nl
    - host: hendrik.ch.tudelft.nl
    - host: rob.ch.tudelft.nl
    - host: bestuur.ch
  tls:
    - hosts:
        - ch.ewi.tudelft.nl
        - ch.its.tudelft.nl
        - hendrik.ch.tudelft.nl
        - rob.ch.tudelft.nl
        - bestuur.ch
      secretName: ingress-ext-tls
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 32M
  name: proxy-cloud
  namespace: default
spec:
  rules:
  - host: cod.ch.tudelft.nl
    http:
      paths:
        - backend:
            serviceName: gcloud
            servicePort: 80
  - host: symposium.ch.tudelft.nl # Legacy redirect for the 2010 site
    http:
      paths:
        - backend:
            serviceName: gcloud
            servicePort: 80
  - host: coh.ewi.tudelft.nl
    http:
      paths:
        - backend:
            serviceName: gcloud
            servicePort: 80
  - host: commissies.tudelft.nl
    http:
      paths:
        - backend:
            serviceName: gcloud
            servicePort: 80
  - host: icpc.tudelft.nl
    http:
      paths:
        - backend:
            serviceName: gcloud
            servicePort: 80
  tls:
    - hosts:
        - symposium.ch.tudelft.nl
        - commissies.ch.tudelft.nl
        - coh.ch.tudelft.nl
        - cod.ch.tudelft.nl
        - icpc.tudelft.nl
      secretName: ingress-ext-tls
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: ingress-ext-tls
  namespace: default
spec:
  secretName: ingress-ext-tls
  dnsNames:
    - ch.tudelft.nl
    - www.ch.tudelft.nl
    - alumni.ch.tudelft.nl
    - businesstour.ch.tudelft.nl
    - ch.ewi.tudelft.nl
    - ch.its.tudelft.nl
    - coh.ewi.tudelft.nl
    - cod.ch.tudelft.nl
    - commissies.ch.tudelft.nl
    - connect.ch.tudelft.nl
    - dkp.tudelft.nl
    - files.ch.tudelft.nl
    - hendrik.ch.tudelft.nl
    - icpc.tudelft.nl
    - rob.ch.tudelft.nl
    - symposium.ch.tudelft.nl
    - studyvisit.ch.tudelft.nl
    - www.icpc.tudelft.nl
    - bestuur.ch
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
