apiVersion: v1
kind: Service
metadata:
  name: website-gke
  namespace: default
spec:
  externalName: website.wisv.ch
  type: ExternalName
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/upstream-vhost: "website.wisv.ch"
    nginx.ingress.kubernetes.io/proxy-ssl-name: "website.wisv.ch"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 32M
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^/events(.*)$ https://events.wisv.ch$1;
      rewrite ^/choice2(.*)$ https://choice.wisv.ch$1;
      rewrite ^/wiki(.*)$ https://wiki.wisv.ch$1;
  name: ch
  namespace: default
spec:
  rules:
    - host: ch.tudelft.nl
      http:
        paths:
          - path: /
            backend:
              serviceName: website-gke
              servicePort: 443
  tls:
    - hosts:
        - ch.tudelft.nl
        - www.ch.tudelft.nl
      secretName: ingress-ext-tls
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/temporal-redirect: https://ch.tudelft.nl
  name: redirect-ch
  namespace: default
spec:
  rules:
    - host: ch.ewi.tudelft.nl
    - host: ch.its.tudelft.nl
    - host: hendrik.ch.tudelft.nl
    - host: bestuur.ch
  tls:
    - hosts:
        - ch.ewi.tudelft.nl
        - ch.its.tudelft.nl
        - hendrik.ch.tudelft.nl
        - bestuur.ch
      secretName: ingress-ext-tls
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: ingress-ext-tls
  namespace: default
spec:
  secretName: ingress-ext-tls
  dnsNames:
    - ch.tudelft.nl
    - www.ch.tudelft.nl
    - ch.ewi.tudelft.nl
    - ch.its.tudelft.nl
    - connect.ch.tudelft.nl
    - hendrik.ch.tudelft.nl
    - icpc.tudelft.nl
    - www.icpc.tudelft.nl
    - bestuur.ch
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
