---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dienst2
  name: dienst2
  namespace: default
  annotations:
    fluxcd.io/automated: "true"
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: dienst2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dienst2
    spec:
      containers:
        - args:
            - gunicorn
            - --workers=4
          env:
            - name: OIDC_RP_CLIENT_ID
              value: dienst2
            - name: OIDC_RP_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: OIDC_RP_CLIENT_SECRET
                  name: dienst2
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: SECRET_KEY
                  name: dienst2
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: DATABASE_URL
                  name: dienst2
            - name: CACHE_URL
              value: locmemcache://
            - name: GOOGLE_SERVICE_ACCOUNT_DELEGATED_USER
              value: root@ch.tudelft.nl
          image: ghcr.io/wisvch/dienst2:20230409-659b740@sha256:1772571fc6a54827da78016a6232fe90187630109305306208d6e86b2e2ef2cc
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 8000
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          name: gunicorn
          ports:
            - containerPort: 8000
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 8000
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          resources:
            limits:
              cpu: 400m
              memory: 512Mi
            requests:
              cpu: 400m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /config
              name: config
              readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: config
          secret:
            defaultMode: 420
            secretName: dienst2
