---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dienst2
  name: dienst2
  namespace: default
  annotations:
    fluxcd.io/automated: "true"
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: dienst2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dienst2
    spec:
      containers:
        - args:
            - gunicorn
            - --workers=4
          env:
            - name: OIDC_RP_CLIENT_ID
              value: dienst2
            - name: OIDC_RP_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: OIDC_RP_CLIENT_SECRET
                  name: dienst2
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: SECRET_KEY
                  name: dienst2
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: DATABASE_URL
                  name: dienst2
            - name: CACHE_URL
              value: locmemcache://
            - name: GOOGLE_SERVICE_ACCOUNT_DELEGATED_USER
              value: root@ch.tudelft.nl
          image: ghcr.io/wisvch/dienst2:20230410-d5ebb0b@sha256:c64209079f8aca623ed079ace1ba80fa6d824ffeaa30c3b7a87e21b20c0c455c
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 8000
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          name: gunicorn
          ports:
            - containerPort: 8000
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 8000
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          resources:
            limits:
              cpu: 400m
              memory: 512Mi
            requests:
              cpu: 400m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /srv/google-service-account.json
              name: google-service-account
              subPath: google-service-account.json
              readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: google-service-account
          secret:
            defaultMode: 420
            secretName: dienst2
