---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chtv
  namespace: w3cie
  labels:
    app: chtv
  annotations:
    fluxcd.io/automated: 'true'
spec:
  replicas: 0
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: chtv
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: chtv
      name: chtv
    spec:
      containers:
      - image: ghcr.io/wisvch/chtv:20220107-f810fbc
        imagePullPolicy: IfNotPresent
        name: chtv
        resources:
          limits:
            cpu: 500m
            memory: 200Mi
          requests:
            cpu: 10m
            memory: 200Mi
        securityContext:
          privileged: false
          runAsNonRoot: false
