---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
  namespace: w3cie
  labels:
    app: website
  annotations:
    fluxcd.io/automated: 'true'
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: website
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      name: website
      labels:
        app: website
    spec:
      containers:
      - name: website
        image: ghcr.io/wisvch/website:20230302-387697a@sha256:7f375ee0967f36e3d48a3ad81650de241d737c0ddcd169d1b9581ab961662774
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        env:
        - name: WORDPRESS_DB_HOST
          value: joost.chnet
        - name: WORDPRESS_DB_USER
          value: w3cie_wp
        - name: WORDPRESS_DB_NAME
          value: w3cie_wp
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: wordpress-db-password
        - name: WORDPRESS_DB_PREFIX
          value: chtud59_
        - name: DIENST2_API_URL
          value: https://dienst2.ch.tudelft.nl/ldb/api/v3/
        - name: DIENST2_API_TOKEN
          valueFrom:
            secretKeyRef:
              key: password
              name: website-dienst2-api-token
        - name: W3CIE_THEME
          value: https://github.com/WISVCH/rechallenge/archive/master.zip
        - name: W3CIE_PLUGINS
          value: disable-comments,disable-search,post-types-order,wordpress-seo,https://github.com/daggerhart/openid-connect-generic/archive/dev.zip,https://github.com/WISVCH/wisvch-wordpress-plugin/archive/master.zip,depublish-posts,redirection,ewww-image-optimizer,photo-gallery,10web-manager,instagram-feed,wp-statistics
        - name: APACHE_LOG_DIR
          value: /var/log/apache/
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: 300m
            memory: 500Mi
        securityContext:
          runAsNonRoot: false
        volumeMounts:
        - mountPath: /var/www/html/wp-content
          name: website-storage
      volumes:
      - name: website-storage
        persistentVolumeClaim:
          claimName: website-storage
