apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: symposium-2017
  name: symposium-2017
  namespace: default
spec:
  replicas: 2
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: symposium-2017
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: symposium-2017
    spec:
      containers:
      - image: quay.io/wisvch/symposium-2017:32
        imagePullPolicy: IfNotPresent
        name: symposium-2017
        ports:
        - containerPort: 80
          protocol: TCP
          name: http
        securityContext:
          runAsNonRoot: false
