apiVersion: apps/v1
kind: Deployment
metadata:
  name: www-misc
  namespace: default
  labels:
    app: www-misc
  annotations:
    fluxcd.io/automated: 'true'
spec:
  replicas: 2
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: www-misc
  strategy:
    type: RollingUpdate
  template:
    metadata:
      name: www-misc
      labels:
        app: www-misc
    spec:
      containers:
      - name: www-misc
        image: quay.io/wisvch/www-misc:14
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        resources:
          limits:
            cpu: 10m
            memory: 32Mi
          requests:
            cpu: 10m
            memory: 32Mi
        securityContext:
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
        volumeMounts:
        - name: tmpfs
          mountPath: /tmp
      volumes:
      - name: tmpfs
        emptyDir:
          medium: Memory
