apiVersion: v1
kind: Service
metadata:
  name: www-misc
  namespace: default
  labels:
    app: www-misc
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: www-misc
  sessionAffinity: None
  type: ClusterIP
